-- Generated INSERTs for table `company_profiles` with derived relationship
SET NAMES utf8mb4;
SET time_zone = '+07:00';
INSERT INTO `company_profiles` (code, name, address, spesific_location, phone, email, website, relationship, npwp, tax_invoice_to, tax_invoice_address, created_at, updated_at) VALUES
('CP.00451', ' AP. SAUDARA ', 'SIMPANG GAMBIR 
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00256', 'ABING DT', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00015', 'ACE', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00132', 'ACUN', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00491', 'ADI FREELANCE ', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00247', 'ADI GMP', 'BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00060', 'AFUK', 'BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00286', 'AGUNG WIBOWO', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00235', 'AHAP BSH', 'MEDAN', NULL, '082361615968', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00025', 'AHUK', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00143', 'AKENG ', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00300', 'ALBERT GARUDA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00471', 'AP. A3', 'JL. WILLIAM ISKANDAR DALAN LIDANG 
PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00114', 'AP. A4', 'PYB', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00425', 'AP. ABADI JAYA', 'JL. RAKYAT
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00251', 'AP. ADIMAKMUR', 'JL. TANJUNG MORAWA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00294', 'AP. AFILAZA', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00166', 'AP. AGUNG MULIA', 'JLN . B.ZEIN HAMID KOMP CITRA BARU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00094', 'AP. AINUL', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00303', 'AP. AIR MAS', 'JL. NGUMBAN SURBAKTI NO. 16 MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00187', 'AP. AISYAH STABAT', 'STABAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00122', 'AP. AISYAH TANAH SERIBU', 'TANAH SERIBU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00145', 'AP. AK JAYA', 'DELI TUA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00084', 'AP. ALHADI', 'PALOPAT/PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00417', 'AP. ALMAGIAN ', 'JL. JAMIN GINTING  NO. 105 A
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00051', 'AP. ALMAQVIRA', 'JL. JAMIN GINTING 
SP. TUNTUNGAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00367', 'AP. ALPHA FARMA', 'JLN. DENAI
MEDAN DENAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00050', 'AP. ANDA (FD)', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00271', 'AP. ANDALAN FARMA', 'JL.AR HAKIM MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00078', 'AP. ANDALAN JASA IBU', 'UNTE MANIS - PSP', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00055', 'AP. ANGEL', 'JL. JAMIN GINTING
 P. BULAN. PSR V', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00216', 'AP. ANISA', 'PANDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00360', 'AP. ANTARA', 'AEK NABARA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00386', 'AP. ANUGERAH ', 'JEURAM-NAGAN RAYA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00188', 'AP. ANUGRAH (TELUK DALAM)', 'JL.JEND A YANI N0.8 TELUK DALAM (NISEL)', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00437', 'AP. ANUGRAH GNG SITOLI', 'GNG SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00067', 'AP. ANUGRAH PERSADA', 'JL.JAMIN GINTING SP. TUNTUNGAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00490', 'AP. ARAFA ', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00517', 'AP. ARES', 'JL. KAPTEN MUCHTAR BASRI NO. 94
DEKAT UMSU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00083', 'AP. ARKHA', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00265', 'AP. ARKHA 2', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00057', 'AP. ARMA JAYA', 'JL. PINTU AIR IV NO.452
SIMALINGKAR B', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00470', 'AP. ARRAFA', 'JL. SILANDIT LK II NO 38
PSD SELATAN ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00356', 'AP. ASIA', 'PADANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00376', 'AP. BAHTERA FARMA', 'JLN. IRIAN BARAT 
SAMPALI. DELI SERDANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00510', 'AP. BAKTI', 'JLN. ISKANDAR MUDA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
(' AUTO', 'AP. BATARA', 'JL.SELESAI LANGKAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00420', 'AP. BERJAYA FARMA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00520', 'AP. BERKAH ', 'JL. MENTENG II RT.000 - RW.00
TEGAL SARI II
MEDAN AREA. KOTA MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00034', 'AP. BERKAT MANDIRI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00038', 'AP. BERLIAN SARI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00431', 'AP. BERSAMA ', 'AEK NABARA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00295', 'AP. BERSAMA (MDN)', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00117', 'AP. BERSAMA (TAMER)', 'TANAH MERAH', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00184', 'AP. BERSATU', 'BRANDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00066', 'AP. BERSINAR FARMA', 'JL. TUNTUNGAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00118', 'AP. BETESDA', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00375', 'AP. BETHESDA (KBJ)', 'KABANJAHE', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00464', 'AP. BINJAI FARMA', 'JL. BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00026', 'AP. BINTANG', 'JL. TEMBAKAU RAYA NO. 8
PRUMNAS SIMALINGKAR', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00419', 'AP. BN ', 'PANYABUNGAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00219', 'AP. BONA 1', 'JL. JAMIN GINTING NO.128', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00212', 'AP. BONA RAYA', 'JL.PANGLIMA DENAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00318', 'AP. BRAYAN', 'JL.PUTRI HIJAU.No. 181', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00238', 'AP. BROMO JAYA', 'BROMO', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00301', 'AP. BUDI MURNI', 'TANJUNG PURA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00142', 'AP. CAHAYA', 'LHOKSUKON. ACEH', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00344', 'AP. CAHAYA 71A', 'JL. BROMO. MEDAN DENAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00368', 'AP. CAHAYA GEMILANG ', 'JLN. LETDA SUJONO 
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00197', 'AP. CAHAYA RAYA', 'JLN. TITI PAPAN MARELAN PSR V
MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00096', 'AP. CARDINAL', 'G. SITOLI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00293', 'AP. CARLOS', 'JLN. Panjaitan No 62', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00388', 'AP. CEMERLANG FARMA', 'JL. BROMO
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00245', 'AP. CENDANA ABADI', 'JL. PELITA I
KOMP. GRAHA PELITA 1 NO. A1
MEDAN PERJUANGAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00492', 'AP. CENTRAL', 'JL. PROF HM YAMIN NO 271-A', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00414', 'AP. CENTRAL MEDIKA', 'MEDAN
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00249', 'AP. CENTRAL STABAT', 'STABAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00258', 'AP. CIPTA', 'JL. JAMIN GINTING NO.221 P.BULAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00403', 'AP. CITRA ', 'JL. ASAM KUMBANG. SIMPANG BUNGA ASOKA
SUNGGAL MEDAN.', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00435', 'AP. CITRA FARMA', 'JL. DENAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00052', 'AP. CITRA HAGANTA', 'JL. JAMIN GINTING 
P. BULAN. PASAR BARU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00182', 'AP. CITRA MANDIRI ', 'BRAHRANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00416', 'AP. CITRA PAKAM', 'PAKAM', NULL, '081396929723', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00179', 'AP. CITRA SETIA', 'JALAN. SUDIRMAN BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00239', 'AP. CITRA STABAT', 'STABAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00177', 'AP. CLARIA', 'JL. PANGKALAN SUSU
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00148', 'AP. CM2', 'KM12.5', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00317', 'AP. D24', 'JL. DIPONEGORO G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00518', 'AP. DAFFA FARMA ', 'JL. TEMBUNG PSR 10
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00505', 'AP. DAINANG', 'SINGKUANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00183', 'AP. DAMAI SEJAHTERA', 'BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00350', 'AP. DAST RAYA', 'JL. UTAMA II BANDAR KALIPA
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00411', 'AP. DAULAY', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00040', 'AP. DEAR', 'JL. JAMIN GINTING PASAR II PADANG BULAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00484', 'AP. DEAR DELI TUA', 'JL. BESAR DELI TUA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00224', 'AP. DEARDO', 'JL. MEDAN BATANG KUIS.DUSUN 3', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00472', 'AP. DEARMA ', 'SARIBU DOLOK 
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00497', 'AP. DESY FARMA', 'TABUYUNG 
KEC MUARA BATANG GADIS
KAB MANDAILING NATAL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00374', 'AP. DHARMA BAKTI', 'JLN. VETERAN NO 49a
BRASTAGI', NULL, '081262248497', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00366', 'AP. DIAN FARMA', 'JLN. LETDA SUJONO NO. 3
MEDAN TEMBUNG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00395', 'AP. DOA IBU', 'JL. KEBUN KOPI NO. 8A MARENDAL 1
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00155', 'AP. DUMA', 'BALIGE', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00045', 'AP. EDATA', 'JL. FLAMBOYAN RAYA SP. MELATI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00499', 'AP. EKA JAYA', 'JL. MAYJEN H. T. RIZAL NURDIN NO. 239
KEC. PANTAI CERMIN
KABUPATEN SERDANG BEDAGAI ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00511', 'AP. EKA JAYA SBG', 'SIBOLGA ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00512', 'AP. ELORA', 'JLN. PADANGSIDEMPUAN.PINANGSORI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00326', 'AP. ERNALA', 'JL. JAMIN GINTING. SP SELAYANG
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00392', 'AP. FAMILY TEMBUNG', 'JL. BUSTAMAN 
TEMBUNG', NULL, '085373168889', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00090', 'AP. FITRAH', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00003', 'AP. FLORA', 'JL. FLAMBOYAN RAYA
SP. MELATI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00043', 'AP. FORTUNA', 'JL. AMAL SUNGGAL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00072', 'AP. FRENCH FARMA', 'SIDIKALANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00044', 'AP. GABE FAMILY', 'JL. FLAMBOYAN RAYA SP. MELATI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00041', 'AP. GABE REZEKI', 'JL. DELI TUA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00167', 'AP. GENKI FARMA', 'JALAN. BRIDJEND KATAMSO', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00319', 'AP. GIOVANNO', 'JL. TAMBANG MINYAK. PANGKALAN SUSU', NULL, '0822 7298 9009', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00307', 'AP. GRACE', 'JL. TANJUNG PURA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00413', 'AP. GRAHA MEDIKA', 'JLN. BANGKA 86 
MEDAN
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00116', 'AP. GRISELLA', 'TANAH MERAH', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00033', 'AP. GUNA FARMA', 'JL. SP. SIMALINGKAR', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00054', 'AP. HARAPAN JAYA', 'JL. JAMIN GINTING
SP SELAYANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00280', 'AP. HARAPAN JAYA LAUT DENDANG', 'JLN. PERTAHAN. PERCUT SEI TUAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00111', 'AP. HARVEST', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00377', 'AP. HERLINA ', 'JLN. AHMAD YANI NO. 54 
KOTACANE. KEC. BABUSSALAM ', NULL, '085270903791', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00176', 'AP. HIDUP SEHAT', 'BRAHRANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00494', 'AP. HIDUP SEHAT SUNGGAL', 'JALAN SUNGGAL 
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00082', 'AP. HIKMAH', 'PANDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00093', 'AP. HOLLY', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00203', 'AP. HUMISAR', 'DOLOK MASIHOL', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00483', 'AP. HUSNA FARMA ', 'BATANG TORU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00086', 'AP. IMAN', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00158', 'AP. INDAH FARMA', 'JALAN BINJAI - KUALA 
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00440', 'AP. INSANI ( PSP )', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00147', 'AP. INSANI FARMA (TTG)', 'JALAN HM.YAMIN 
TEBING TINGGI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00193', 'AP. INTAN', 'BESITANG', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00468', 'AP. INTAN FARMA (PSP)', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00192', 'AP. JASA FARMA', 'JL.JEND SUDIRMAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00253', 'AP. JASANTA', 'JL.JAMIN GINTING NO.197 P.BULAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00447', 'AP. JAYA ABADI', 'JL. JAMIN GINTING
. SP SELAYANG MEDAN ', NULL, '0853-7233-5699', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00302', 'AP. JOAN', 'NIAS SELATAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00047', 'AP. JUNI', 'JL. DELI TUA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00495', 'AP. KARUNIA ', 'JL. SIKAMBING NO. 59C MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00343', 'AP. KARYA BERSAMA ', 'JL. SEKSAMA. MEDAN DENAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00162', 'AP. KARYA FARMA', 'JALAN SEI AGUL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00001', 'AP. KARYA RAYA', 'JL. KARYA JAYA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00105', 'AP. KASIH AGAVE', 'JL. JAMIN GINTING', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00080', 'AP. KELAN ANGGINA', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00429', 'AP. KELUARGA', 'JL. ALUMINIUM RAYA TIMUR
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00106', 'AP. KELUARGA ( PSP )', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00345', 'AP. KEMBAR JAYA ', 'JLN. PELANGI NO. 8
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00410', 'AP. KITA ', 'JLN. IMAM BONJOL 
NO. 123A 
PADANGSIDIMPUAN 
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00223', 'AP. KITA FARMA', 'BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00457', 'AP. KRAKATAU', 'JL. KRAKATAU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00453', 'AP. KUALUH BERKAH', 'JALAN. TUASAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00048', 'AP. KURNIA ', 'JL. KARYA WISATA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00422', 'AP. KURNIA FARMA', 'CIKAMPAK', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00261', 'AP. KURNIA TR', 'TARUTUNG', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00194', 'AP. KWALA FARMA', 'JLN. KWALA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00400', 'AP. LASHOT SIABU', 'JALUR 2 MANDAILING NATAL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00401', 'AP. LASHOT SINUNUKAN', 'PASAR SINUNUKAN 3 MANDAILING NATAL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00467', 'AP. LIDYA ', 'KEC. NATAL
KEL. PASAR 1 NATAL
MANDAILING NATAL
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00073', 'AP. MADINA ', 'PYB', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00370', 'AP. MAJU FARMA', 'JLN. MARELAN RAYA PSR IV NO. 111
MARELAN-MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00441', 'AP. MAKMUR ', 'SAYUR MATINGGI
SIMP.TANO TOMBANGAN 
TAPANULI SELATAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00312', 'AP. MAKMUR MEDIKA', 'JL. MAKMUR TEMBUNG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00208', 'AP. MANGATAS', NULL, NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00291', 'AP. MANJUR', 'JL. KEBUN KOPI NO 5.B', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00274', 'AP. MANNA PORSEA', NULL, NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00110', 'AP. MARAMPAR', 'SIABU', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00140', 'AP. MARAS SELATAN', 'TJ. MORAWA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00243', 'AP. MARI SEHAT', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00058', 'AP. MARIO FARMA', 'JL. A.H. NASUTION 
SIMALINGKAR B', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00097', 'AP. MARTUA', 'JL. DELI TUA
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00476', 'AP. MEDI FARMA', 'JLN PASAR3 NO2
KRAKATAU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00516', 'AP. MELINA', 'JL. SETIA BUDI LINGKUNGAN X NO. 10. HELVETIA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00349', 'AP. MENTARI', 'BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00087', 'AP. MERDEKA', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00069', 'AP. MERLIN', 'G. SITOLI
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00141', 'AP. MILION', 'SIBOLGA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00469', 'AP. MISIDI FARMA', 'JL. CEMPAKA .KAMPUNG LALANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00309', 'AP. MITRA BERSAMA', 'JL. ISMAILIYAH HALAT MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00348', 'AP. MITRA LORA', 'JLN. MUSYAWARAH. KEC. PERCUT SEI TUAN
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00206', 'AP. MUBAROK', 'BATANG TORU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00506', 'AP. MUDAH REZEKI', 'JLN. A.M.D.KOMPLEKS
GREEN RESIDENCE B5
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00519', 'AP. MULIA FARMA (RPP)', 'RANTAU PARAPAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00175', 'AP. MURAH KOMPLIT', 'JALAN DINONEGORO NO 318B
GUNUNG SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00501', 'AP. MURAH KOMPLIT MEDAN', 'JL. JAMIN GINTING NO. 46A ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00290', 'AP. MUTIARA', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00108', 'AP. NADZAR', 'PSP
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00338', 'AP. NAGABE', 'JL. IMAM BONJOL (PSP)', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00198', 'AP. NAHDI', 'JLN.PERINTIS KEMERDEKAAN BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00189', 'AP. NANDA', 'G.SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00306', 'AP. NASIONAL (SM. RAJA)', 'JL. SM RAJA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00103', 'AP. NASIONAL A.F', 'JALAN PADANG BULAN (MEDAN)', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00479', 'AP. NASIONAL DELI TUA', 'JL. DELI TUA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00287', 'AP. NASIONAL FARMA', 'JALAN DENAI. SUKARAMAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00513', 'AP. NASIONAL KARYA', 'JALAN KARYA JAYA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00321', 'AP. NASIONAL RINGROAD', 'JLN. RINGROAD', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00240', 'AP. NASIONAL SIDIKALANG', 'SIDIKALANG', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00315', 'AP. NASIONAL SUNGGAL', 'JLN. SUNGGAL. PERUM SUNGGAL CENTER A8', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00502', 'AP. NATONGGI', 'DESA SIUNGGAM
KEC.PADANG BOLAK TENGGARA
KAB.PALUTA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00042', 'AP. NAULI', 'JL. KARYA JAYA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00396', 'AP. NAULI FARMA', 'PASAR SIGALANGAN BATANG ANGKOLA TAPANULI SELATAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00522', 'AP. NAULI FARMA TANJUNG ANOM', 'TANJUNG ANOM', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00284', 'AP. NAULI. F', 'JALAN PASAR 1
SETIA BUDI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00465', 'AP. NEW HARAPAN ', 'BRAYAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00211', 'AP. NIAS 24', 'G.SITOLI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00152', 'AP. NIKO', 'JL. TANJUNG ANOM', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00088', 'AP. NINA', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00120', 'AP. NUSANTARA (BLG)', 'BALIGE', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00144', 'AP. OLO AU', 'JL. JAMIN GINTING', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00209', 'AP. PAHLAWAN', 'BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00137', 'AP. PALAS', 'SIBUHUAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00068', 'AP. PANCUR BATU', 'JL. JAMIN GINTING NO. 123
PANCUR BATU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00089', 'AP. PANGABEAN', 'SIBOLGA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00079', 'AP. PANYABUNGAN', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00409', 'AP. PARULIAN JAYA', 'DESA JANJI MARTOGU
KEC. BUKIT MELINTANG 
KAB. MANDAILING NATAL
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00445', 'AP. PELITA', 'DALAN LIDANG
PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00415', 'AP. PELITA 3', 'JLN. VETERAN PASAR IX
MARELAN MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00406', 'AP. PEMBANGUNAN ', 'JL. PEMBANGUNAN KM 12', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00362', 'AP. PERMAI ', 'BAGAN BATU', NULL, '081378992022', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00264', 'AP. PERMATA', 'RANTAU PRAPAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00121', 'AP. PERMATA FARMA', 'JL. AH. NASUTION NO. 11 B MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00091', 'AP. PUTRI', 'PSP', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00204', 'AP. PUTRI 2', 'PSP', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00036', 'AP. PUTROU BUNGSU', 'TAKENGON', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00046', 'AP. RAFIF', 'JL. KARYA JAYA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00081', 'AP. RAHMA', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00107', 'AP. RAHMAT', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00311', 'AP. RAHMAT SETIA 2', 'JL. DENAI JERMAL NO. 1', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00181', 'AP. RAMBUNG FARMA', 'BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00423', 'AP. RAPHAEL ', 'JALAN TEMPULING', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00296', 'AP. RAPHITA JAYA', 'JL. PROF. HM YAMIN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00190', 'AP. RAYA 3', 'JL.KELAMBIR 5 ', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00267', 'AP. RAYA 4', 'JL. RUMAH POTONG HEWAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00342', 'AP. RAYA JAYA ', 'JL. VETERAN MARELAN ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00257', 'AP. RAYADO', 'JL. SUASA RAYA MABAR HILIR', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00276', 'AP. RAZAN', 'JLN. GUMIT', NULL, '085831973814', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00154', 'AP. RESTU', 'JALAN SUDIRMAN
BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00498', 'AP. RIDHO ', 'JL. KARYA JAYA . JOHOR', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00346', 'AP. RIZKY', 'JL. AYAHANDA 
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00489', 'AP. ROGANDA  (POKEN SELASA)', 'RONDAMAN DOLOK . SUMUT 
KAB.PADANG LAWAS UTARA .PORTIBI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00482', 'AP. ROYAL FARMA', 'BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00383', 'AP. SAFIRA ', 'JL. BILAL 
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00421', 'AP. SAHABAT', 'SIGAMBAL. RANTAU PRAPAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00477', 'AP. SAHABAT (PBU)', 'PERBAUNGAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00205', 'AP. SAKTI FAMILY', 'JL.TANJUNG SLAMAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00168', 'AP. SANDY', 'BUKIT TINGGI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00394', 'AP. SANJAYA FARMA', 'AEK KANOPAN', NULL, '0811656980', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00165', 'AP. SAUDARA ', 'JALAN SM.RAJA NO 324', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00452', 'AP. SAUDARA (SG)', 'SIMPANG GAMBIR', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00380', 'AP. SAUDARA KEMBAR', 'KUTACANE', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00104', 'AP. SEGAR', 'SIBOLGA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00095', 'AP. SEHAT', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00430', 'AP. SEHAT (SBG)', 'SIBOLGA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00313', 'AP. SEHAT BERSAMA', 'TEMBUNG MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00185', 'AP. SEHAT FARMA', 'BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00279', 'AP. SEHAT PORSEA', 'PORSEA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00428', 'AP. SEHATI ', 'JLN. GARUDA
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00478', 'AP. SEHATI (LANGGA  PAYUNG)', 'LANGGA PAYUNG ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00053', 'AP. SELAYANG', 'JL. SETIA BUDI NO.1
SP. SELAYANG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00500', 'AP. SERASI ', NULL, NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00186', 'AP. SETIA FARMA', 'JL.TA.HAMZAH BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00289', 'AP. SEVA', 'JL. BERANDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00378', 'AP. SHAKA ', 'KUTACANE', NULL, '081361094489', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00399', 'AP. SIBUHUAN ', 'PADANG LAWAS', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00232', 'AP. SIDEMPUAN', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00488', 'AP. SINAR BARU ', 'JL.SYAILENDRA  NO.21 D', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00436', 'AP. SINAR NATURAL', 'JL. GATOT SUBROTO SP. S. PARMAN ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00434', 'AP. SINEMBAH', 'KAMP. LALANG 
SIMP. PIRDAM 
BAGAN BATU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00496', 'AP. SINERGI ', 'JL.AR. HAKIM 
MEDAN ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00092', 'AP. SION', 'G. SITOLI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00077', 'AP. SIPIROK', 'SIPIROK', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00363', 'AP. SRI DEWI', 'MARTUBUNG. MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00202', 'AP. STELLA', 'TANJUNG PURA - LANGKAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00030', 'AP. SUKARAMAI', 'JL. A.R. HAKIM NO.166', NULL, '061-7357530', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00504', 'AP. SUKARAME ', 'JL. RAJAWALI NO. 46
MEDAN SUNGGAL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00237', 'AP. SUMBER BERKARYA', 'JL. DELI TUA KM 10.5', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00178', 'AP. SUMBER JAYA', 'JL.SULTAN SERDANG DSN 1 TJ.MORAWA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00201', 'AP. SURYA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00071', 'AP. SURYA ANGGINA', 'G. TUA
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00196', 'AP. SURYA FARMA', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00222', 'AP. SURYA MEDIKA', 'JALAN SEI MENCIRIM NO 3 (BLKG PAJAK PRINGAN)
MEDAN ', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00138', 'AP. SYIFA', 'TANJUNG PURA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00005', 'AP. SYUKUR', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00281', 'AP. TAMA', 'TEMBUNG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00332', 'AP. TAMASMA', 'JLN. JAMIN GINTING. PANCUR BATU 
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00487', 'AP. TAMBA JAYA (SGM)', 'SIGAMBAL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00391', 'AP. TAMBA JAYA B.TORU', 'BATANG TORU', NULL, '082258564311', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00129', 'AP. TAMBAH JAYA', 'G. TUA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00463', 'AP. TAMBAH JAYA  (PYB)', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00230', 'AP. TANDEM', 'TANDEM', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00503', 'AP. TARULI JAYA', 'JL.RAJA INAL SIREGAR .BATUNADUA
SIDEMPUAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00426', 'AP. TEMPULING', 'JL. TEMPULING
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00341', 'AP. TERANG FARMA', 'JL. BESAR. PASAR 8 TEMBUNG
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00119', 'AP. TESALONIKA', 'TARUTUNG', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00124', 'AP. TOMMY', 'TANDAM', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00521', 'AP. TRI JAYA', 'HAMPARAN PERAK ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00282', 'AP. ULI PARNA', 'STUDION TELADAN TIMUR', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00037', 'AP. ULINA', 'JL. JAMIN GINTING SP PASAR BARU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00432', 'AP. VICTORY FARMA', 'JL. KELAMBIR V NO. 77
SUNGGAL.MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00485', 'AP. VITA SARI ', 'KABANJAHE', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00361', 'AP. WAWAN', 'MEULABOH', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00379', 'AP. WENDI FARMA', 'JL. SUNGGAL NO. 8
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00180', 'AP. YAKIN SEHAT', 'JL.AHMAD YANI BINJAI', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00115', 'AP. YANTONST/IBU & ANAK', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00418', 'AP. YASER ', 'PASAR PANYABUNGAN NO. 124
PANYABUNGAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00433', 'APOTEK  SINEMBAH ', 'SIMP. PIRDAM 
BAGAN BATU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00389', 'APOTEK BAKTI MEDIKA FARMA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00316', 'ARI NOVELL', 'MEDAN
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00027', 'AWI', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00150', 'AYEK', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00242', 'AYU ACEH', 'ACEH', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00228', 'BAYU', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00020', 'BUDI BIOLYSIN', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00393', 'BUDI DEXA AAM', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00214', 'CEKNUR', 'LHOKSUMAWE', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00021', 'CHANDRA KAZU', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00384', 'CHERRY SHOP', 'JL. BANGAU NO. 56 
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00064', 'CV. BUANA MAS', NULL, NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00262', 'DAHRI HJ', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00299', 'DAMAR INF', NULL, NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00252', 'DEDEK', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00298', 'DIAN MEPRO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00269', 'DIAN TEMPO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00323', 'DIKA INDOFARMA', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00339', 'DIRA MERSI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00438', 'DR. FERNANDA HUTAURUK', 'JLN KENARI NO 805', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00462', 'Dr. INDAH', 'JL. KAPTEN MUSLIM ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00109', 'DR. IRSAN', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00444', 'Dr. JOSUA ', 'MDN - BINJAI KM 7', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00475', 'DR. LENNY WIJAYA', 'JALAN THAMRIN NO.138', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00443', 'Dr. LINDA SAFITRI LUBIS Sp.KK', 'JL.T. AMIR HAMZAH 
KOMPLEK TAMAN INDAH BLOK B NO 1
BINJAI
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00466', 'Dr. MARIANA', 'BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00446', 'Dr. RUDYN PANJAITAN', 'JL. SUTRISNO NO 246
MDN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00439', 'DR. YOSEPHINA', 'PEKANBARU ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00255', 'DWI PHAPROS', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00062', 'EDY BRUTU', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00263', 'ERELA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00123', 'ERWIN', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00218', 'ERWIN (MBMS)', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00285', 'FEBRI DEXA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00340', 'FEBRI KIMIA FARMA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00024', 'FERRY', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00225', 'FIKRI GMP', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00236', 'FIKRI MBMS', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00514', 'FREELANCE (EB)', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00014', 'FREELANCE (HR)', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00493', 'GELENG ', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00159', 'HARDY MBMS', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00358', 'HENDRA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00244', 'HENDRIK AAM', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00266', 'HERI PROMED', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00322', 'HERRY MGS', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00246', 'IKAPHARMINDO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00369', 'ILHAM', 'BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00327', 'JIHAN BERNO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00221', 'JIMMY (MBS)', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00135', 'JOHN', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00248', 'KALBE', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00126', 'KIMIA FARMA', 'JL. SISINGAMANGARAJA KM9 NO.59A MEDAN
20218', NULL, '061-7860468', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00381', 'KLINIK ANDALUSIA', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00371', 'KLINIK BOBY', 'PEKAN BARU', NULL, '081279924640', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00448', 'KLINIK JUMINAH MARBUN ', 'JL. AIR BERSIH UJUNG MEDAN ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00297', 'LEO', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00508', 'MEDISEN ', NULL, NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00329', 'MEDY', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00146', 'MENSA BINASUKSES PT', 'JL. TEMPURA NO.36 KEL. SEIKAMBING B
KEC MEDAN SUNGGAL       ', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00273', 'MEPRO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00270', 'MICHAEL', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00259', 'MIKE', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00161', 'MOKTAR', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00250', 'MOMONGAN (MEKADA)', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00061', 'MPI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00328', 'NASIR KALBE', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00335', 'NOVEL', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00305', 'OSCAR STJ', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00136', 'PANJANG', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00007', 'PETER', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00130', 'PETER GD', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00460', 'PKS', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00292', 'PT. ADYA  ARTHA  ABADI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00473', 'PT. AGUNG BERINGIN LESTARI ', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00359', 'PT. AKAJAYA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00234', 'PT. ALFAZZA JAYA MAS', 'JL. MERCI RAYA NO.72', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00157', 'PT. ANTARMITRA SEMBADA', 'JL.ASOKA MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00049', 'PT. ANUGERAH PHARMINDO LESTARI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00314', 'PT. ANUGERAH TAIPAN MAKMUR', 'KOMP. GRAND CEMARA ASRI JLN. NO. 8II KOTA MEDAN ', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00133', 'PT. ANUGRAH ARGON MEDICA', 'JL. SEI SERAYU 102 TANJUNG REJO MEDAN ', NULL, '061-4567422', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00354', 'PT. AQSA MANDIRI JAYA ', NULL, NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00016', 'PT. BHAKTI SEHAT HUSADA', 'JL. SETIA LUHUR NO. 9C. KEL DWIKORA', NULL, '089103730400', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00304', 'PT. BINA CATUR MARGA', 'JL. PANJANG 8 D-E', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00112', 'PT. BINA SAN PRIMA', 'JL. GATOT SUBROTO KM 5.5', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00100', 'PT. BINA SEHAT HOSLAB', 'JL. SETIA LUHUR KOMP. GRIYA MILLENIUM BLOK C 6 MEDAN', NULL, '061-8467701', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00098', 'PT. BINTANG MEDIKA BERSAMA MEDAN', 'JL. PUKAT BANTING II/ MESTIKA. KOMP JASMINE MESTIKA REGENCY NO. 107 H&I. KEL. BANTAN. KEC. MEDAN TEMBUNG. KOTA MEDAN. PROP. SUMATERA UTARA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00029', 'PT. CAMAR USAHA TATA', 'JL. K.H. WAHID HASYIM NO. 98/96A', NULL, '061-4533682//061-4569143', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00390', 'PT. CENTURY FRANCHISINDO UTAMA', NULL, NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00019', 'PT. CHARISMA METCO', 'JL. RAYA BEKASI KM 21 
JAKARTA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00063', 'PT. DAYA MUDA AGUNG', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00364', 'PT. DIMAS ANDALAS MEDIKA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00076', 'PT. DISTRINDO BINTANG AGUNG', 'JL. PERWIRA UTAMA NO.19. KEL. SUNGGAL.
KEC MEDAN SUNGGAL. MEDAN', NULL, '061-647745/HP(WA)081376630577', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00174', 'PT. DISTRIVERSA BUANAMAS', 'JL.GATOT SUBROTO NO.248', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00113', 'PT. DOS NI ROHA', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00002', 'PT. DWI TUNGGAL', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00018', 'PT. ENSEVAL PUTERA MEGATRADING TBK.', 'JL. MEDAN- TJ MORAWA KM9.5', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00351', 'PT. ERA KIAT WICAKSANA', NULL, NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00170', 'PT. GARUDA PERKASA INTIMEDIKA', 'JL.BERJAYA NO.88 I-J', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00173', 'PT. GLOBAL MITRA PRIMA', 'JL.BUDI LUHUR NO.96 MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00382', 'PT. GLOBAL PHARMA INDONESIA', NULL, NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00065', 'PT. GRAHA TRIAGO MEDIKA', 'JL.WILLIEM ISKANDAR KOMPLEK MMTC 
WAREHOUSE NO.26B', NULL, '061-800884688 (HUNTING)', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00365', 'PT. GRAND DUTA PHARMINDO', 'JL. PASAR 6 TENGAH NO. 30
BANDAR KHALIPA. KEC. PERCUT SEI TUAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00012', 'PT. GREAT DELI FARMA', 'JL. TUANKU TAMBUSANI
KOMPEK NANGKA RAYA PERMAI
BLOK F1 NO. 3-4 PEKAN BARU
', NULL, '0761-572044//572045//572231', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00022', 'PT. HOSLAB MEDIKA FARMA', 'JL. TILAK NO. 123-G', NULL, '061-7333626', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00032', 'PT. INDOFARMA GLOBAL MEDIKA', 'KOMP INFINIA PARK. JL. DR SAHARJO NO. 45.
BLOK B-86 JAKARTA SELATAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00035', 'PT. KEBAYORAN PHARMA', 'JL. RAYA MEDAN-BINJAI 224', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00325', 'PT. KWATRO MANDIRI EKAVISI', 'JL.CARINGIN No. 345 EF', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00199', 'PT. LENKO SURYA PERKASA', 'JLN.TOMAT NO.4 MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00481', 'PT. MEGA INTER DISTRINDO', 'JL. LETSU UJUNG KOMPLEKS PERGUDANGAN INTAN BLOK B NO.B3A', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00099', 'PT. MEGAH TETAP SAKTI', 'JL. DUYUNG NO.84-CD MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00011', 'PT. MEKADA ABADI', 'JL. KAPTEN MUSLIM NO. 235 MEDAN HELVETIA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00013', 'PT. MENARA ANUGERAH SENTOSA', 'JL. RS HAJI KOMP. MUTIARA RESIDENCE 
BLOK R NO. 18/19/20 ', NULL, '061-6632300//061-6632717', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00458', 'PT. MENJANGAN ENAM', 'SEMARANG', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00028', 'PT. MERAPI UTAMA PHARMA', 'JL. CILOSARI 23 CIKINI-MENTENG
JAKARTA', NULL, '021-3141908', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00017', 'PT. MESTIKA SAKTI', 'JL. VETERAN NO. 64-66-68-70', NULL, '061-4523118', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00006', 'PT. METRO ARTHA PRAKARSA', 'JL. PANAH NO.14 MEDAN', NULL, '061-6612161//061-80088095', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00031', 'PT. MILLENIUM PHARMACON INTERNASIONAL Tbk.', 'JL. BERINGIN NO. 02 SUNGGAL (CABANG MEDAN)', NULL, '061-80440887//061-80440888', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00010', 'PT. MITRA BINAMULTI SEJAHTERA', 'MEDAN
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00210', 'PT. MITRA MULTI MANUNGGAL', 'JL.PADANG GOLF CBD MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00134', 'PT. PARIT PADANG GLOBAL', 'JL. BUDI LUHUR NO. 196-A MEDAN HELVETIA MEDAN 20123', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00171', 'PT. PENTA VALENT', 'JL.KAPTEN MUSLIM KOMPLEK MEGACOM CENTER BLOCK B25-27 KEL. DWIKORA KEC. MEDAN HELVETIA 
', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00509', 'PT. PUTRA TANJUNG MEDICARE', 'JL. CEMARA NO. 88 AD-AE
KOMPLEK RUKO GRAND CEMARA ASRI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00355', 'PT. RADIANT SENTRAL NUTRINDO', NULL, NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00127', 'PT. SAN PRIMA SEJATI', NULL, NULL, '061-42066287', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00195', 'PT. SAPTA SARI TAMA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00101', 'PT. SIDARTA HUSADA', 'JL. ABDULLAH LUBIS NO. 25 MEDAN', NULL, '061-4567845 (HUNTING)', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00023', 'PT. SINAR PERMATA LESTARI', 'JL. SIDORUKUN NO. 107 A.B.C', NULL, '061-6619555', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00172', 'PT. SINARMAS DISTRIBUSI NUSANTARA', 'JL.MEDAN RAYA TG.MORAWA KM 11.5', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00515', 'PT. SUMATERA PUTERA FARMASI', 'JL. MEDAN DELI', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00009', 'PT. SURYA TARA JAYA', 'JL. A.R. HAKIM GG.BAKUNG NO. 5A-B', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00207', 'PT. TEMPO', 'TG.MORAWA DELI SERDANG', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00059', 'PT. TRI SAPTA JAYA', 'JL. RING ROAD. RUKO NO.100-102.
LINGKUNGAN X', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00227', 'PT. UNITED DICO CITAS', 'JL SEI BINGEI MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00102', 'PT. WICANA INDO NUGRAHA ', 'JL. NEGARA NO. 64 CDE MEDAN', NULL, '061-4519223', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00337', 'RAJAB DRUIR', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00039', 'RAJAWALI NUSINDO', 'JL. JEND. GATOT SUBROTO KM5 NO.146', NULL, '061-8452104/8454062', NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00131', 'RICHARD', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00200', 'RIDHO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00226', 'RIKI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00334', 'ROBY BERNO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00254', 'RONI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00153', 'RS. BIDADARI', 'JALAN KEBUN LADA
BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00455', 'RS. FULL BETHESDA ', 'JL.BINJAI KM 10 ', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00156', 'RS. PUTRI BIDADARI', 'LANGKAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00233', 'RSUD. GUNUNG TUA', 'G.TUA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00149', 'SIKO', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00336', 'SISWANTO BERNO', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00454', 'STEVEN MENARA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00331', 'SUTRESNO INDOFARMA', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00278', 'TITO MGS', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00074', 'TO. ALIMA', 'G.TUA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00151', 'TO. ASIA', 'JLN. JENDRAL SUDIRMAN
BINJAI', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00220', 'TO. BERKAT', 'BINJAI KUALA', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00405', 'TO. BINSAR', 'SIMPANG BALIMBING - NATAL', NULL, '082163098975', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00310', 'TO. BUDIMAN JAYA ', 'JL. AR. HAKIM', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00231', 'TO. GABY', 'SAMOSIR', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00075', 'TO. ILHAM', 'G. TUA
', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00128', 'TO. ISTIQOMAH', 'PYB', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00385', 'TO. JAMU AGUS', 'JL. KLAMBIR V KP LALANG
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00275', 'TO. JAMU INDRA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00424', 'TO. JAYA RAYA', 'SIGAMBAL
RANTAU PRAPAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00480', 'TO. KUTALIMBARU ', 'KUTALIMBARU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00217', 'TO. LINGGA', 'P. SIANTAR', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00125', 'TO. MANGATAS', 'PSP', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00449', 'TO. MEGA FARMA', 'SIMP. GEREJA HKBP TAMBUNAN 
BALIGE', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00459', 'TO. MITRA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00387', 'TO. MITRA ABADI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier', NULL, NULL, NULL, NOW(), NOW()),
('CP.00139', 'TO. MUTIARA', 'TANAH MERAH', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00213', 'TO. PANDU', 'JL.PANDU MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00004', 'TO. PEMBANGUNAN', 'JL. PEMBANGUNAN KM 12 NO.1', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00372', 'TO. PLUS', 'JL. HM YAMIN No. 84
KISARAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00402', 'TO. PULAU BARU ', 'JL. BANDUNG
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00352', 'TO. RIZA KARYA', 'JL. KAPTEN MUSLIM
MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00085', 'TO. SAMBAS', 'SIBOLGA', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00427', 'TO. SAMPURNA FARMA ', 'SIMPANG RANTO JIOR
SAMPING INDOMARET 
KEC. LABUSEL', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00474', 'TO. SARI FARMA', 'JL. SISINGAMANGARAJA KM 1O HUTAPAUNG
KEC.POLLUNG 
KAB.HUMBANG HASUNDUTAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00373', 'TO. SENTOSA', 'RANTAU PRAPAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00277', 'TO. SERASI MANDAONI MATITI', 'MANDAONI MATITI 1', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00241', 'TO. SINAR LANGKAT', 'LANGKAT', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00398', 'TO. TAMBA JAYA SUMBAR', 'SIMP. SMK HARAPAN BANGSA SORIK PANTI PASAMAN BARAT SUMATRA BARAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00461', 'TO. TUNAS HARAPAN', 'RANTO PRAPAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00486', 'TO. ULINA PANCUR BATU', 'PANCUR BATU', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00450', 'TO. WELOFA', 'NAMORAMBE', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00442', 'TO. YOWAN (MDN)', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00404', 'TO.BINSAR', 'SIMPANG BALIMBING - NATAL
', NULL, '082163098975', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00397', 'TO.TAMBA JAYA SUMBAR', 'SIMP. SMK HARAPAN BANGSA SORIK PANTI PASAMAN BARAT SUMATRA BARAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00412', 'TO.TUNAS HARAPAN ', 'RANTAU PRAPAT', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00260', 'TOHADI', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00229', 'TOKO 88', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00333', 'TOKO TEODIN', 'PULAU TELLO. NIAS SELATAN', NULL, '082167366179', NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00456', 'TONI 3 M', 'JL. SEJATI 
KOMP. JATI PERMAI NO 8
KAMPUNG DURIAN





', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW())
;
INSERT INTO `company_profiles` (code, name, address, spesific_location, phone, email, website, relationship, npwp, tax_invoice_to, tax_invoice_address, created_at, updated_at) VALUES
('CP.00160', 'VIANDY STJ', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00283', 'VITAMIN MART', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00507', 'WENDI METRO', 'MEDAN', NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00268', 'WILLIAM', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00308', 'WILSON NIAS', NULL, NULL, NULL, NULL, NULL, 'customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00008', 'YANSEN', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00163', 'YUSRA', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW()),
('CP.00408', 'ZICO', 'MEDAN', NULL, NULL, NULL, NULL, 'supplier & customer', NULL, NULL, NULL, NOW(), NOW())
;